* waygate

An interactive companion map to the Wheel of Time series by Robert
Jordan.

* Installation

** Dependencies

*** Frontend (React)

Instatiate with create-react-app

#+BEGIN_SRC sh
yarn add react-bootstrap bootstrap
#+END_SRC

react-map-interaction (my fork)

*** Backend (Django)

This project use =pipenv= for dependencies management.

Use =pipenv install= to install the following packages from Pipfile.

- django
- django_restframework
- django-cors-header
- psycopg2

* References

** Setup React frontend

Tutorial: Intro to React

https://reactjs.org/tutorial/tutorial.html

** Setup Django backend

Writing your first Django app (Series)

https://docs.djangoproject.com/en/3.0/intro/tutorial01/

Build a To-Do application Using Django and React

https://scotch.io/tutorials/build-a-to-do-application-using-django-and-react

** Setup PostgreSQL

Setup PostgreSQL database

https://wiki.archlinux.org/index.php/PostgreSQL

Setup Django to use PostgreSQL backend

https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-14-04

* Tips & Tricks

** Reset sequence in Postgresql

#+BEGIN_SRC sql
ALTER SEQUENCE map_chapter_id_seq RESTART;
UPDATE map_chapter set id = DEFAULT;
#+END_SRC

** Setting up Postgresql on ZFS server

[[https://www.2ndquadrant.com/en/blog/pg-phriday-postgres-zfs/][Tutorial]] (Use postgres version 10)

As ROOT
Create ZFS dataset

#+BEGIN_SRC sh
zfs create -o recordsize=8K \
             -o primarycache=metadata \
             -o mountpoint=/var/lib/postgres \
             -o logbias=throughput \
              <pool>/postgres
#+END_SRC

As ROOT
Create PostgresSQL cluster

#+BEGIN_SRC sh
pg_createcluster 12 zfs -D /rpool/postgres
systemctl daemon-reload

pg_conftool 12 zfs set shared_buffers 4GB
pg_conftool 12 zfs set work_mem 12MB
pg_conftool 12 zfs set maintenance_work_mem 1GB
pg_conftool 12 zfs set random_page_cost 2.0
pg_conftool 12 zfs set effective_cache_size 40GB

systemctl start postgresql@12-zfs

#+END_SRC

As =postgres= user.

#+BEGIN_SRC
createdb waygate
pgbench -i -s 100 waygate
#+END_SRC

* Other resources

- Book list https://en.wikipedia.org/wiki/The_Wheel_of_Time
- Chapter summary https://dragonmount.com/news/book-news/booksummaries/
- List of Point of View Characters https://wot.fandom.com/wiki/List_of_Point_of_View_Characters
- Color scheme https://material.io/design/color/the-color-system.html#tools-for-picking-colors
- Using HTML5 Canvas with React, Sarah Bruce https://blog.cloudboost.io/using-html5-canvas-with-react-ff7d93f5dc76
- Statistical Analysis https://wot.fandom.com/wiki/Statistical_analysis
- TarValon.net https://library.tarvalon.net/index.php?title=Chapter_Summaries
- AJAX and APIS - React https://reactjs.org/docs/faq-ajax.html
- react-map-interaction https://github.com/transcriptic/react-map-interaction
- react-custom-scrollbars https://github.com/malte-wessel/react-custom-scrollbars
- styled-components https://styled-components.com/docs
- icon https://styled-components.com/docs
