# Generated by Django 3.0.6 on 2020-06-08 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveSmallIntegerField()),
                ('chapter_name', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='map.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=200)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('use_white_text', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrators', to='map.Chapter')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrators', to='map.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('type', models.CharField(choices=[('ld', 'Travel by land'), ('se', 'Travel by sea'), ('tv', 'Travel by Gateway'), ('wg', 'Travel by Waygate'), ('bt', 'Battle'), ('cp', 'Camping'), ('ev', 'Event')], default='ld', max_length=100)),
                ('narrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='map.Narrator')),
            ],
        ),
    ]
