# Generated by Django 3.0.6 on 2020-05-09 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.FloatField()),
                ('start_y', models.FloatField()),
                ('end_x', models.FloatField()),
                ('end_y', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('chapter_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Chapter')),
            ],
        ),
    ]
