# Generated by Django 3.0.6 on 2020-05-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200511_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Chapter')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Character')),
            ],
        ),
        migrations.RenameModel(
            old_name='MapPin',
            new_name='Pin',
        ),
        migrations.DeleteModel(
            name='PointOfView',
        ),
        migrations.AlterField(
            model_name='pin',
            name='point_of_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.PoV'),
        ),
    ]
