# Generated by Django 3.0.6 on 2020-05-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20200519_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='chapter_number',
            new_name='chapter',
        ),
    ]
