# Generated by Django 3.0.6 on 2020-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200519_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='character',
            name='lastname',
            field=models.CharField(default='Gaboo', max_length=200),
            preserve_default=False,
        ),
    ]
