# Generated by Django 3.0.6 on 2020-05-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20200519_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='character',
            name='lastname',
        ),
    ]
