# Generated by Django 3.0.6 on 2020-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20200519_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
