# Generated by Django 3.0.6 on 2020-05-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20200519_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='type',
            field=models.CharField(choices=[('ld', 'Travlling by land'), ('tv', 'Travelling by Gateway'), ('sk', 'Skimming by Gatebay')], default='ld', max_length=100),
        ),
    ]
