# Generated by Django 3.0.6 on 2020-05-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20200519_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='type',
            field=models.CharField(choices=[('ld', 'Travel by land'), ('se', 'Travel by sea'), ('tv', 'Travel by Gateway'), ('sk', 'Skim by Gatebay')], default='ld', max_length=100),
        ),
    ]
