# Generated by Django 3.0.6 on 2020-05-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20200520_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='pov',
        ),
    ]
