# Generated by Django 3.0.6 on 2020-05-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_remove_pin_pov'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='pov',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.PoV'),
            preserve_default=False,
        ),
    ]
