# Generated by Django 3.0.6 on 2020-05-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_pin_pov'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoV',
            new_name='Narrator',
        ),
        migrations.RenameModel(
            old_name='Pin',
            new_name='Point',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='pov',
            new_name='narrator',
        ),
    ]
