# Generated by Django 3.0.6 on 2020-05-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_auto_20200520_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='end_x',
            new_name='x',
        ),
        migrations.RemoveField(
            model_name='point',
            name='end_y',
        ),
        migrations.RemoveField(
            model_name='point',
            name='start_x',
        ),
        migrations.RemoveField(
            model_name='point',
            name='start_y',
        ),
        migrations.AddField(
            model_name='point',
            name='y',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('ld', 'Travel by land'), ('se', 'Travel by sea'), ('tv', 'Travel by Gateway'), ('wg', 'Travel by Waygate'), ('bt', 'Battle'), ('cp', 'Camping'), ('ev', 'Event')], default='ld', max_length=100),
        ),
    ]
