# Generated by Django 3.0.6 on 2020-05-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20200520_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='type',
            field=models.CharField(choices=[('ld', 'Travel by land'), ('se', 'Travel by sea'), ('tv', 'Travel by Gateway'), ('wg', 'Travel by Waygate'), ('bt', 'Battle'), ('cp', 'Camping'), ('ev', 'Event')], default='ev', max_length=100),
        ),
    ]
