# Generated by Django 3.0.6 on 2020-05-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_auto_20200520_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
