# Generated by Django 3.0.6 on 2020-05-28 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_auto_20200520_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='character',
            name='use_white_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='map.Book'),
        ),
        migrations.AlterField(
            model_name='narrator',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrators', to='map.Chapter'),
        ),
        migrations.AlterField(
            model_name='point',
            name='narrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='map.Narrator'),
        ),
    ]
