# Generated by Django 3.0.6 on 2020-05-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_auto_20200521_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='use_white_text',
            field=models.BooleanField(default=True),
        ),
    ]
