# Generated by Django 3.0.6 on 2020-06-01 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_auto_20200528_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrator',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrators', to='map.Character'),
        ),
    ]
